### ISSUE TITLE
building nodejs image currently fails :(

### ISSUE THREAD

**Issue by Dieterbe** [raintank/raintank-docker#11]
from Dockerfile (i just added curl):

```
FROM library/ubuntu

RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install nodejs nodejs-legacy nodejs-dev npm git curl
```

```
Get:141 http://archive.ubuntu.com/ubuntu/ trusty/universe node-slide all 1.1.4-1 [6118 B]
Get:142 http://archive.ubuntu.com/ubuntu/ trusty/universe nodejs-legacy all 0.10.25~dfsg2-2ubuntu1 [14.6 kB]
Get:143 http://archive.ubuntu.com/ubuntu/ trusty/universe npm all 1.3.10~dfsg-1 [442 kB]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main linux-libc-dev amd64 3.13.0-52.85
  404  Not Found [IP: 91.189.91.15 80]
Fetched 45.6 MB in 21s (2149 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-52.85_amd64.deb  404  Not Found [IP: 91.189.91.15 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
INFO[0027] The command [/bin/sh -c apt-get -y install nodejs nodejs-legacy nodejs-dev npm git curl] returned a non-zero code: 100 

```

changed to 

```
FROM library/ubuntu

RUN apt-get update && apt-get -y upgrade

RUN apt-get -y install --fix-missing nodejs nodejs-legacy nodejs-dev npm git curl
```

same shit :(

**Comment by woodsaj** [comment]
This is most likely because `RUN apt-get update && apt-get -y upgrade` has been cached and is not being re-executed.

You need to rebuild without cache `docker build --no-cache` or delete any existing raintank/nodejs images with `docker rmi`

For a more long term solution we should probably combine the update and install commands into one.

```
RUN apt-get update &&\
        apt-get -y upgrade &&\
        apt-get -y install nodejs nodejs-legacy nodejs-dev npm git curl
```

**Comment by Dieterbe** [comment]
you're right. that seems to have fixed it.
my docker build is now stuck at a point it often gets stuck at:

```
(...)
npm http GET https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/get-stdin
npm http 200 https://registry.npmjs.org/graceful-readlink
npm http GET https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz
npm http 200 https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.1.1.tgz
npm http 200 https://registry.npmjs.org/jsonpointer/-/jsonpointer-1.1.0.tgz
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/get-stdin
npm http 304 https://registry.npmjs.org/ansi-regex
npm http 200 https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz
npm http 200 https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz
npm http GET https://registry.npmjs.org/is-property
npm http 200 https://registry.npmjs.org/is-property
npm http GET https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz
npm http 200 https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz

```

sometimes killing the build and restarting it works fine.

**Comment by ridelabs** [comment]
Not related to your project, however as an FYI: I was getting this until I added a proper nameserver

RUN echo -ne "nameserver 8.8.8.8\nnameserver 8.8.4.4\n" >> /etc/resolv.conf && \
    apt-get update && \
    apt-get upgrade && \
    apt-get install -y vim

**Comment by Dieterbe** [comment]
@rideswitch you were getting what exactly until you added the name server? dns lookup errors?

**Comment by ridelabs** [comment]
@Dieterbe 
Sorry, I just saw this response.  Note that I only mentioned it because I found this conversation when I was googling to try to find an answer to my problem.  I notice above that you were actually resolving the name, just getting 404's for some reason...  So, you can delete my comment if you feel it is not relevant.  However to answer your question:  Yes, I was seeing name resolution problems like this:
- ping -c 1 google.com
  ping: unknown host
- apt-get update
  Err http://httpredir.debian.org jessie InRelease
  Err http://security.debian.org jessie/updates InRelease  
  Err http://httpredir.debian.org jessie-updates InRelease
  ...
- pip install --upgrade pip
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known'))': /simple/pip/

When I added in the google nameservers, things work fine.
